apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend-service
  namespaceSelector:
    matchNames:
      - fca-dev
      - fca
  endpoints:
    - port: http
      path: /metrics
      interval: 15s