apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      name: server
  template:
    metadata:
      labels:
        name: server
    spec:
      containers:
        - name: server
          image: avinashrajure/fca-server:498c6d5cae0b8b8f30bfedef5d9fe7065fd94b20
          ports:
            - containerPort: 7777
          envFrom:
          - secretRef:
              name: server-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    name: server
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
